# Generated by Django 6.0.6 on 2026-06-07 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="space",
            name="type",
        ),
        migrations.AddField(
            model_name="space",
            name="space_description",
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="SpaceOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="booking.space"
                    ),
                ),
            ],
        ),
    ]
