# Generated by Django 6.0.6 on 2026-06-07 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_remove_space_type_space_space_description_spaceowner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spaceowner",
            name="space",
        ),
        migrations.AddField(
            model_name="space",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spaces",
                to="booking.spaceowner",
            ),
            preserve_default=False,
        ),
    ]
