# Generated by Django 6.0.6 on 2026-06-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_remove_spaceowner_space_space_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="end_time",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="start_time",
            field=models.DateField(),
        ),
    ]
