# Generated by Django 6.0.6 on 2026-06-09 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_alter_reservation_end_time_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
